language: bash
sudo: required
dist: trusty
services:
  - docker
script:
  - ./start-ci.sh
  - ../Outloud/continuous-integration/git-pull.sh $PROJECT_NAME
  - ../Outloud/continuous-integration/docker-build.sh $ENVIRONMENT
  - ../Outloud/continuous-integration/docker-test.sh $IMAGE_NAME $ENVIRONMENT
after_success:
  - ../Outloud/continuous-integration/docker-publish.sh $IMAGE_NAME $REGISTRY $TRAVIS_BRANCH
notifications:
  slack: outloud-talk:TGwStb79G3lZNaeh7f5aiGIP
  email:
    on_success: never
    on_failure: never