language: bash
sudo: required
dist: trusty
services:
  - docker
script:
  - ./start-ci.sh
  - ../Outloud/continuous-integration/git-pull.sh $PROJECT_NAME
  - ../Outloud/continuous-integration/docker-build.sh $ENVIRONMENT
  - ../Outloud/continuous-integration/docker-test.sh $IMAGE_NAME $ENVIRONMENT
  - ../Outloud/continuous-integration/docker-clean.sh $IMAGE_NAME $ENVIRONMENT
#   - /docker-test.sh $IMAGE_NAME_API $TRAVIS_BUILD_ID $ENVIRONMENT
#   - ./scripts/docker-clean.sh $IMAGE_NAME_API
# after_success:
#   - ./scripts/docker-publish.sh $IMAGE_NAME_API $TRAVIS_BUILD_ID $REGISTRY_URL $REGISTRY_USERNAME $REGISTRY_PASSWORD
#   - ./scripts/docker-publish.sh $IMAGE_NAME_CLIENT $TRAVIS_BUILD_ID $REGISTRY_URL $REGISTRY_USERNAME $REGISTRY_PASSWORD
#   - ./scripts/docker-publish.sh $IMAGE_NAME_PROXY $TRAVIS_BUILD_ID $REGISTRY_URL $REGISTRY_USERNAME $REGISTRY_PASSWORD
notifications:
  slack: outloud-talk:TGwStb79G3lZNaeh7f5aiGIP
  email:
    on_success: never
    on_failure: never