// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Outloud.QuizService.Persistance;

namespace Outloud.QuizService.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20181120221856_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Outloud.QuizService.Persistance.Models.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Outloud.QuizService.Persistance.Models.QuizEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryEntityId");

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryEntityId");

                    b.ToTable("Quizes");
                });

            modelBuilder.Entity("Outloud.QuizService.Persistance.Models.WordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<Guid?>("QuizEntityId");

                    b.HasKey("Id");

                    b.HasIndex("QuizEntityId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Outloud.QuizService.Persistance.Models.QuizEntity", b =>
                {
                    b.HasOne("Outloud.QuizService.Persistance.Models.CategoryEntity")
                        .WithMany("Quizes")
                        .HasForeignKey("CategoryEntityId");
                });

            modelBuilder.Entity("Outloud.QuizService.Persistance.Models.WordEntity", b =>
                {
                    b.HasOne("Outloud.QuizService.Persistance.Models.QuizEntity")
                        .WithMany("Words")
                        .HasForeignKey("QuizEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
